### PR TITLE
convert payload back to []byte

### PR DESCRIPTION
**Pull request by hendratommy**
When inserting new record, pgx treat the payload as custom type, and since the column is an json column, pgx try to marshal the payload into json which is already encoded into json. This causing the value of payload stored as base64 string.

### CODE REVIEW

**Comment by MichalZalecki** [comment]
@roblaszczak @m110 Could you take a look? I'm using `pgx` and experienced the same issue. `message.Payload` type is not recognized as `[]byte` so it gets encoded.

**Comment by m110** [comment]
Hey, I'm on it - sorry about the delay.

**Comment by m110** [comment]
Thank you for the contribution @hendratommy and again, I'm sorry for such long delay with the review!

**Comment by hendratommy** [comment]
No problem. Glad to help! 👍

**Pull request merged**
